//go:build linux

package main

import (
	"encoding/binary"
	"errors"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"sync"
	"syscall"
)

// The Wayland wire protocol, as much of it as a data-control client needs:
// messages of 32-bit words on a Unix socket, file descriptors beside them as
// SCM_RIGHTS. Each message is the object id, then the size in bytes (header
// included) in the high half of a word and the opcode in the low half, then
// the arguments. Integers are the host's byte order, which on every
// architecture the module ships for is little-endian.
//
// It is written here rather than taken from a library because the protocols
// it speaks (ext-data-control-v1 and wlr-data-control-unstable-v1) are
// generated by none of the maintained pure-Go Wayland clients, and linking
// libwayland would take the module off pure Go.

const wlHeaderSize = 8

var (
	errWlClosed   = errors.New("the Wayland connection closed")
	errWlProtocol = errors.New("wayland protocol error")
	errNoRuntime  = errors.New("XDG_RUNTIME_DIR is unset")
)

// wlMessage is one event as it arrived.
type wlMessage struct {
	object uint32
	opcode uint16
	args   []byte
	conn   *wlConn
}

// uint reads the next 32-bit argument.
func (m *wlMessage) uint() (uint32, error) {
	if len(m.args) < 4 {
		return 0, fmt.Errorf("%w: object %d opcode %d is short", errWlProtocol, m.object, m.opcode)
	}
	v := binary.LittleEndian.Uint32(m.args)
	m.args = m.args[4:]
	return v, nil
}

// string reads the next string argument: its length including the NUL, then
// the bytes padded to a word.
func (m *wlMessage) string() (string, error) {
	n, err := m.uint()
	if err != nil {
		return "", err
	}
	padded := int((n + 3) &^ 3)
	if n == 0 || padded > len(m.args) {
		return "", fmt.Errorf(
			"%w: object %d opcode %d has a bad string",
			errWlProtocol,
			m.object,
			m.opcode,
		)
	}
	s := string(m.args[:n-1])
	m.args = m.args[padded:]
	return s, nil
}

// fd takes the next file descriptor that arrived with the messages.
func (m *wlMessage) fd() (int, error) {
	return m.conn.takeFD()
}

// wlArgs builds a request's arguments.
type wlArgs []byte

func (a wlArgs) uint(v uint32) wlArgs { return binary.LittleEndian.AppendUint32(a, v) }

func (a wlArgs) string(s string) wlArgs {
	n := uint32(len(s) + 1) //nolint:gosec // G115: a MIME type or interface name
	a = a.uint(n)
	a = append(a, s...)
	for range int((n+3)&^3) - len(s) {
		a = append(a, 0)
	}
	return a
}

// wlConn is a client connection to a compositor.
type wlConn struct {
	sock *net.UnixConn

	wmu sync.Mutex // one request on the wire at a time

	idMu sync.Mutex
	next uint32
	free []uint32

	fdMu sync.Mutex
	fds  []int
}

// wlSocket is the path of display's socket: WAYLAND_DISPLAY names a socket in
// XDG_RUNTIME_DIR unless it is a path itself.
func wlSocket(display, runtimeDir string) (string, error) {
	if filepath.IsAbs(display) {
		return display, nil
	}
	if runtimeDir == "" {
		return "", fmt.Errorf(
			"%w, so the Wayland display %q cannot be found",
			errNoRuntime,
			display,
		)
	}
	return filepath.Join(runtimeDir, display), nil
}

func dialWayland(path string) (*wlConn, error) {
	sock, err := net.DialUnix("unix", nil, &net.UnixAddr{Name: path, Net: "unix"})
	if err != nil {
		return nil, fmt.Errorf("connecting to the Wayland display at %s: %w", path, err)
	}
	// Object 1 is wl_display; the client allocates from 2.
	return &wlConn{sock: sock, next: 2}, nil
}

func (c *wlConn) close() error {
	c.fdMu.Lock()
	for _, fd := range c.fds {
		_ = syscall.Close(fd)
	}
	c.fds = nil
	c.fdMu.Unlock()
	return c.sock.Close() //nolint:wrapcheck // closing our own socket
}

// newID allocates an object id, reusing those the compositor released:
// libwayland keeps a client's objects in an array indexed by id, so ids that
// only ever grow would grow the compositor's array for the life of the module.
func (c *wlConn) newID() uint32 {
	c.idMu.Lock()
	defer c.idMu.Unlock()
	if n := len(c.free); n > 0 {
		id := c.free[n-1]
		c.free = c.free[:n-1]
		return id
	}
	id := c.next
	c.next++
	return id
}

// release returns an id the compositor deleted.
func (c *wlConn) release(id uint32) {
	c.idMu.Lock()
	defer c.idMu.Unlock()
	c.free = append(c.free, id)
}

// send writes one request, with fd beside it when fd is not -1.
func (c *wlConn) send(object uint32, opcode uint16, args wlArgs, fd int) error {
	size := wlHeaderSize + len(args)
	msg := make([]byte, 0, size)
	msg = binary.LittleEndian.AppendUint32(msg, object)
	word := uint32(size)<<16 | uint32(opcode) //nolint:gosec // G115: a message is under 4 KiB
	msg = binary.LittleEndian.AppendUint32(msg, word)
	msg = append(msg, args...)
	var oob []byte
	if fd >= 0 {
		oob = syscall.UnixRights(fd)
	}
	c.wmu.Lock()
	defer c.wmu.Unlock()
	if _, _, err := c.sock.WriteMsgUnix(msg, oob, nil); err != nil {
		return fmt.Errorf("%w: %w", errWlClosed, err)
	}
	return nil
}

// read delivers every event to handle until the connection fails or closes.
// File descriptors are queued in the order they arrive, which is the order
// the events that carry them come in.
func (c *wlConn) read(handle func(*wlMessage) error) error {
	buf := make([]byte, 0, 64<<10)
	chunk := make([]byte, 32<<10)
	oob := make([]byte, syscall.CmsgSpace(28*4))
	for {
		n, oobn, _, _, err := c.sock.ReadMsgUnix(chunk, oob)
		if oobn > 0 {
			c.queueFDs(oob[:oobn])
		}
		if err != nil {
			return fmt.Errorf("%w: %w", errWlClosed, err)
		}
		if n == 0 {
			return errWlClosed
		}
		buf = append(buf, chunk[:n]...)
		for len(buf) >= wlHeaderSize {
			size := int(binary.LittleEndian.Uint32(buf[4:]) >> 16)
			if size < wlHeaderSize {
				return fmt.Errorf("%w: a %d-byte message", errWlProtocol, size)
			}
			if len(buf) < size {
				break
			}
			m := &wlMessage{
				object: binary.LittleEndian.Uint32(buf),
				opcode: binary.LittleEndian.Uint16(buf[4:]), // the low half of the word
				args:   append([]byte(nil), buf[wlHeaderSize:size]...),
				conn:   c,
			}
			buf = buf[size:]
			if err := handle(m); err != nil {
				return err
			}
		}
	}
}

func (c *wlConn) queueFDs(oob []byte) {
	msgs, err := syscall.ParseSocketControlMessage(oob)
	if err != nil {
		return
	}
	c.fdMu.Lock()
	defer c.fdMu.Unlock()
	for _, m := range msgs {
		if fds, err := syscall.ParseUnixRights(&m); err == nil {
			c.fds = append(c.fds, fds...)
		}
	}
}

func (c *wlConn) takeFD() (int, error) {
	c.fdMu.Lock()
	defer c.fdMu.Unlock()
	if len(c.fds) == 0 {
		return -1, fmt.Errorf("%w: an event's file descriptor did not arrive", errWlProtocol)
	}
	fd := c.fds[0]
	c.fds = c.fds[1:]
	return fd, nil
}

// pipe is a pipe whose write end is handed to the compositor.
func pipe() (r, w *os.File, err error) {
	r, w, err = os.Pipe()
	if err != nil {
		return nil, nil, fmt.Errorf("creating a pipe: %w", err)
	}
	return r, w, nil
}
